// Self-hosts the web fonts.
//
// The site used to link fonts.googleapis.com, which costs two DNS lookups, two
// TLS handshakes and a render-blocking round trip before any text can paint —
// and required both Google hosts in the Content-Security-Policy.
//
// This script downloads the exact families and weights the stylesheet uses,
// stores the woff2 files under public/assets/fonts/ and writes src/fonts.css with
// the same @font-face rules and unicode-ranges, rewritten to local paths. The
// unicode-range gating is preserved, so a Bulgarian reader still downloads only
// the Cyrillic subsets.
//
// Run it again only to add a weight or refresh the files:
//   node scripts/fetch-fonts.mjs

import fs from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const fontsDir = path.join(rootDir, "public", "assets", "fonts");
const cssPath = path.join(rootDir, "src", "fonts.css");

// Weights are the ones src/styles.css actually declares. Cormorant Garamond has
// no 900 cut, so the few `font-weight: 900` rules stay synthesised as before.
const FAMILIES = [
  "Cormorant+Garamond:wght@600;700",
  "Inter:wght@400;600;700;800",
];

// A modern UA is required — Google serves TTF to unknown clients.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const cssUrl = `https://fonts.googleapis.com/css2?${FAMILIES.map((family) => `family=${family}`).join("&")}&display=swap`;

const response = await fetch(cssUrl, { headers: { "User-Agent": UA } });
if (!response.ok) throw new Error(`Google Fonts CSS request failed: ${response.status}`);
let css = await response.text();

fs.mkdirSync(fontsDir, { recursive: true });

const remoteUrls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]))];
let downloaded = 0;

for (const remote of remoteUrls) {
  // .../s/inter/v20/UcC73Fw…woff2 → inter-UcC73Fw….woff2
  const parts = remote.split("/");
  const family = parts[parts.length - 3];
  const fileName = `${family}-${parts[parts.length - 1]}`;
  const target = path.join(fontsDir, fileName);

  if (!fs.existsSync(target)) {
    const file = await fetch(remote, { headers: { "User-Agent": UA } });
    if (!file.ok) throw new Error(`font download failed (${file.status}): ${remote}`);
    fs.writeFileSync(target, Buffer.from(await file.arrayBuffer()));
    downloaded += 1;
  }

  css = css.split(remote).join(`/assets/fonts/${fileName}`);
}

// Subset → file map, so the prerenderer can preload exactly the file the page's
// language needs (Cyrillic for bg/ru/sr, Greek for el, Latin for the rest)
// instead of hard-coding hashed filenames that change when fonts are refreshed.
const faceBlocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)].map(([, subset, body]) => ({
  subset,
  family: (body.match(/font-family:\s*'([^']+)'/) ?? [])[1],
  weight: Number((body.match(/font-weight:\s*(\d+)/) ?? [])[1]),
  url: (body.match(/url\(([^)]+)\)/) ?? [])[1],
}));

const manifestPath = path.join(rootDir, "src", "generated", "fontManifest.ts");
fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
fs.writeFileSync(
  manifestPath,
  `// GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
//
// Every self-hosted font file with the family, weight and unicode subset it
// serves. src/seo.ts preloads the body-text file for the page's script.

export type FontFace = { family: string; weight: number; subset: string; url: string };

export const fontFaces: FontFace[] = [
${faceBlocks.map((face) => `  { family: "${face.family}", weight: ${face.weight}, subset: "${face.subset}", url: "${face.url}" },`).join("\n")}
];
`,
);

const header = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted @font-face rules, imported by styles.css so Vite inlines them into
 * the single stylesheet. unicode-range is preserved from the Google CSS, so each
 * visitor downloads only the subsets their language needs.
 */
`;

fs.writeFileSync(cssPath, `${header}${css}`);

const bytes = fs
  .readdirSync(fontsDir)
  .reduce((sum, file) => sum + fs.statSync(path.join(fontsDir, file)).size, 0);

console.log(
  `Fonts: ${downloaded} new file(s), ${remoteUrls.length} @font-face sources local, ` +
    `${(bytes / 1024).toFixed(0)} KB on disk across ${fs.readdirSync(fontsDir).length} subsets.`,
);
