import type { EventCategory, EventSeason, LanguageCode } from "./locales/types";

// UI strings for the redesigned Events page. Dates, month and weekday names come
// from Intl.DateTimeFormat(locale), so only these labels are translated here.
export type EventsUiText = {
  // View switcher (tabs)
  viewCalendar: string;
  viewUpcoming: string;
  viewPast: string;
  tablistLabel: string;
  // Hero
  heroSubtitle: string;
  heroCta: string;
  // Section eyebrows / titles
  upcomingEyebrow: string;
  upcomingTitle: string;
  pastEyebrow: string;
  pastTitle: string;
  timelineEyebrow: string;
  timelineTitle: string;
  memoriesEyebrow: string;
  memoriesTitle: string;
  // Filters + categories
  filterAll: string;
  catTraditions: string;
  catChildren: string;
  catNature: string;
  catContest: string;
  catCulture: string;
  // Seasons
  seasonSpring: string;
  seasonSummer: string;
  seasonAutumn: string;
  seasonWinter: string;
  // Buttons / labels
  learnMore: string;
  viewEvent: string;
  viewGallery: string;
  viewPoster: string;
  viewDetails: string;
  todayLabel: string;
  backToToday: string;
  liveNow: string;
  featured: string;
  daysUnit: string; // e.g. "дни"
  countdownSuffix: string; // e.g. "до старта"
  photosUnit: string; // e.g. "снимки"
  prevMonth: string;
  nextMonth: string;
  selectDay: string;
  // Empty states
  emptyUpcoming: string;
  emptyPast: string;
  emptyMonth: string;
  emptyCategory: string;
  clearFilter: string;
  lightboxClose: string;
};

const bg: EventsUiText = {
  viewCalendar: "Календар",
  viewUpcoming: "Предстоящи",
  viewPast: "Минали",
  tablistLabel: "Изгледи на събитията",
  heroSubtitle:
    "Фестивали, фотографски конкурси, традиции, приключения и събития сред природата през цялата година.",
  heroCta: "Разгледай събитията",
  upcomingEyebrow: "Не пропускай",
  upcomingTitle: "Предстоящи събития",
  pastEyebrow: "Архив",
  pastTitle: "Минали събития",
  timelineEyebrow: "През цялата година",
  timelineTitle: "Календар на сезоните",
  memoriesEyebrow: "Спомени",
  memoriesTitle: "Спомени от предишни години",
  filterAll: "Всички събития",
  catTraditions: "Празници и традиции",
  catChildren: "Детски събития",
  catNature: "Природа и приключения",
  catContest: "Конкурси и изложби",
  catCulture: "Култура",
  seasonSpring: "Пролет",
  seasonSummer: "Лято",
  seasonAutumn: "Есен",
  seasonWinter: "Зима",
  learnMore: "Научи повече",
  viewEvent: "Виж събитието",
  viewGallery: "Разгледай галерията",
  viewPoster: "Виж плаката",
  viewDetails: "Виж регламента",
  todayLabel: "Днес",
  backToToday: "Към текущия месец",
  liveNow: "В момента",
  featured: "Акцент",
  daysUnit: "дни",
  countdownSuffix: "до старта",
  photosUnit: "снимки",
  prevMonth: "Предишен месец",
  nextMonth: "Следващ месец",
  selectDay: "Изберете дата, за да видите събитията",
  emptyUpcoming: "Скоро ще обявим нови събития. Разгледай миналите или се върни по-късно.",
  emptyPast: "Все още няма минали събития. Първите спомени тепърва предстоят.",
  emptyMonth: "Няма събития през този месец. Опитайте друг месец.",
  emptyCategory: "Няма събития в тази категория. Изчистете филтъра, за да видите всички.",
  clearFilter: "Изчисти филтъра",
  lightboxClose: "Затвори",
};

const en: EventsUiText = {
  viewCalendar: "Calendar",
  viewUpcoming: "Upcoming",
  viewPast: "Past",
  tablistLabel: "Event views",
  heroSubtitle:
    "Festivals, photography contests, traditions, adventures and events in nature — all year round.",
  heroCta: "Explore the events",
  upcomingEyebrow: "Don't miss",
  upcomingTitle: "Upcoming events",
  pastEyebrow: "Archive",
  pastTitle: "Past events",
  timelineEyebrow: "All year round",
  timelineTitle: "A calendar of seasons",
  memoriesEyebrow: "Memories",
  memoriesTitle: "Memories from past years",
  filterAll: "All events",
  catTraditions: "Holidays & traditions",
  catChildren: "Children's events",
  catNature: "Nature & adventure",
  catContest: "Contests & exhibitions",
  catCulture: "Culture",
  seasonSpring: "Spring",
  seasonSummer: "Summer",
  seasonAutumn: "Autumn",
  seasonWinter: "Winter",
  learnMore: "Learn more",
  viewEvent: "View event",
  viewGallery: "View gallery",
  viewPoster: "View poster",
  viewDetails: "Rules & details",
  todayLabel: "Today",
  backToToday: "Back to current month",
  liveNow: "Happening now",
  featured: "Featured",
  daysUnit: "days",
  countdownSuffix: "to go",
  photosUnit: "photos",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  selectDay: "Select a date to see its events",
  emptyUpcoming: "New events will be announced soon. Browse the past ones or check back later.",
  emptyPast: "No past events yet. The first memories are still to come.",
  emptyMonth: "No events this month. Try another month.",
  emptyCategory: "No events in this category. Clear the filter to see all.",
  clearFilter: "Clear filter",
  lightboxClose: "Close",
};

const de: EventsUiText = {
  viewCalendar: "Kalender",
  viewUpcoming: "Bevorstehend",
  viewPast: "Vergangen",
  tablistLabel: "Veranstaltungsansichten",
  heroSubtitle:
    "Festivals, Fotowettbewerbe, Traditionen, Abenteuer und Veranstaltungen in der Natur — das ganze Jahr über.",
  heroCta: "Veranstaltungen entdecken",
  upcomingEyebrow: "Nicht verpassen",
  upcomingTitle: "Bevorstehende Veranstaltungen",
  pastEyebrow: "Archiv",
  pastTitle: "Vergangene Veranstaltungen",
  timelineEyebrow: "Das ganze Jahr über",
  timelineTitle: "Ein Kalender der Jahreszeiten",
  memoriesEyebrow: "Erinnerungen",
  memoriesTitle: "Erinnerungen aus vergangenen Jahren",
  filterAll: "Alle Veranstaltungen",
  catTraditions: "Feste & Traditionen",
  catChildren: "Veranstaltungen für Kinder",
  catNature: "Natur & Abenteuer",
  catContest: "Wettbewerbe & Ausstellungen",
  catCulture: "Kultur",
  seasonSpring: "Frühling",
  seasonSummer: "Sommer",
  seasonAutumn: "Herbst",
  seasonWinter: "Winter",
  learnMore: "Mehr erfahren",
  viewEvent: "Veranstaltung ansehen",
  viewGallery: "Galerie ansehen",
  viewPoster: "Plakat ansehen",
  viewDetails: "Teilnahmebedingungen",
  todayLabel: "Heute",
  backToToday: "Zurück zum aktuellen Monat",
  liveNow: "Findet gerade statt",
  featured: "Empfohlen",
  daysUnit: "Tage",
  countdownSuffix: "verbleibend",
  photosUnit: "Fotos",
  prevMonth: "Vorheriger Monat",
  nextMonth: "Nächster Monat",
  selectDay: "Wählen Sie ein Datum, um die Veranstaltungen zu sehen",
  emptyUpcoming: "Neue Veranstaltungen werden bald bekannt gegeben. Stöbern Sie in den vergangenen oder schauen Sie später wieder vorbei.",
  emptyPast: "Noch keine vergangenen Veranstaltungen. Die ersten Erinnerungen stehen noch bevor.",
  emptyMonth: "Keine Veranstaltungen in diesem Monat. Versuchen Sie einen anderen Monat.",
  emptyCategory: "Keine Veranstaltungen in dieser Kategorie. Entfernen Sie den Filter, um alle zu sehen.",
  clearFilter: "Filter entfernen",
  lightboxClose: "Schließen",
};

const fr: EventsUiText = {
  viewCalendar: "Calendrier",
  viewUpcoming: "À venir",
  viewPast: "Passés",
  tablistLabel: "Vues des événements",
  heroSubtitle:
    "Festivals, concours de photographie, traditions, aventures et événements en pleine nature — toute l’année.",
  heroCta: "Découvrir les événements",
  upcomingEyebrow: "À ne pas manquer",
  upcomingTitle: "Événements à venir",
  pastEyebrow: "Archives",
  pastTitle: "Événements passés",
  timelineEyebrow: "Toute l’année",
  timelineTitle: "Un calendrier des saisons",
  memoriesEyebrow: "Souvenirs",
  memoriesTitle: "Souvenirs des années passées",
  filterAll: "Tous les événements",
  catTraditions: "Fêtes & traditions",
  catChildren: "Événements pour enfants",
  catNature: "Nature & aventure",
  catContest: "Concours & expositions",
  catCulture: "Culture",
  seasonSpring: "Printemps",
  seasonSummer: "Été",
  seasonAutumn: "Automne",
  seasonWinter: "Hiver",
  learnMore: "En savoir plus",
  viewEvent: "Voir l’événement",
  viewGallery: "Voir la galerie",
  viewPoster: "Voir l’affiche",
  viewDetails: "Règlement et détails",
  todayLabel: "Aujourd’hui",
  backToToday: "Revenir au mois en cours",
  liveNow: "En cours",
  featured: "À la une",
  daysUnit: "jours",
  countdownSuffix: "restants",
  photosUnit: "photos",
  prevMonth: "Mois précédent",
  nextMonth: "Mois suivant",
  selectDay: "Sélectionnez une date pour voir ses événements",
  emptyUpcoming: "De nouveaux événements seront bientôt annoncés. Parcourez les événements passés ou revenez plus tard.",
  emptyPast: "Aucun événement passé pour le moment. Les premiers souvenirs sont encore à venir.",
  emptyMonth: "Aucun événement ce mois-ci. Essayez un autre mois.",
  emptyCategory: "Aucun événement dans cette catégorie. Effacez le filtre pour tout voir.",
  clearFilter: "Effacer le filtre",
  lightboxClose: "Fermer",
};

const es: EventsUiText = {
  viewCalendar: "Calendario",
  viewUpcoming: "Próximos",
  viewPast: "Pasados",
  tablistLabel: "Vistas de eventos",
  heroSubtitle:
    "Festivales, concursos de fotografía, tradiciones, aventuras y eventos en la naturaleza — durante todo el año.",
  heroCta: "Explorar los eventos",
  upcomingEyebrow: "No te lo pierdas",
  upcomingTitle: "Próximos eventos",
  pastEyebrow: "Archivo",
  pastTitle: "Eventos pasados",
  timelineEyebrow: "Durante todo el año",
  timelineTitle: "Un calendario de estaciones",
  memoriesEyebrow: "Recuerdos",
  memoriesTitle: "Recuerdos de años anteriores",
  filterAll: "Todos los eventos",
  catTraditions: "Fiestas y tradiciones",
  catChildren: "Eventos infantiles",
  catNature: "Naturaleza y aventura",
  catContest: "Concursos y exposiciones",
  catCulture: "Cultura",
  seasonSpring: "Primavera",
  seasonSummer: "Verano",
  seasonAutumn: "Otoño",
  seasonWinter: "Invierno",
  learnMore: "Saber más",
  viewEvent: "Ver evento",
  viewGallery: "Ver galería",
  viewPoster: "Ver el cartel",
  viewDetails: "Bases y detalles",
  todayLabel: "Hoy",
  backToToday: "Volver al mes actual",
  liveNow: "Sucediendo ahora",
  featured: "Destacado",
  daysUnit: "días",
  countdownSuffix: "restantes",
  photosUnit: "fotos",
  prevMonth: "Mes anterior",
  nextMonth: "Mes siguiente",
  selectDay: "Selecciona una fecha para ver sus eventos",
  emptyUpcoming: "Pronto se anunciarán nuevos eventos. Explora los pasados o vuelve más tarde.",
  emptyPast: "Aún no hay eventos pasados. Los primeros recuerdos están por llegar.",
  emptyMonth: "No hay eventos este mes. Prueba con otro mes.",
  emptyCategory: "No hay eventos en esta categoría. Borra el filtro para verlos todos.",
  clearFilter: "Borrar filtro",
  lightboxClose: "Cerrar",
};

const it: EventsUiText = {
  viewCalendar: "Calendario",
  viewUpcoming: "In arrivo",
  viewPast: "Passati",
  tablistLabel: "Viste degli eventi",
  heroSubtitle:
    "Festival, concorsi di fotografia, tradizioni, avventure ed eventi nella natura — tutto l’anno.",
  heroCta: "Esplora gli eventi",
  upcomingEyebrow: "Da non perdere",
  upcomingTitle: "Eventi in arrivo",
  pastEyebrow: "Archivio",
  pastTitle: "Eventi passati",
  timelineEyebrow: "Tutto l’anno",
  timelineTitle: "Un calendario delle stagioni",
  memoriesEyebrow: "Ricordi",
  memoriesTitle: "Ricordi degli anni passati",
  filterAll: "Tutti gli eventi",
  catTraditions: "Feste e tradizioni",
  catChildren: "Eventi per bambini",
  catNature: "Natura e avventura",
  catContest: "Concorsi ed esposizioni",
  catCulture: "Cultura",
  seasonSpring: "Primavera",
  seasonSummer: "Estate",
  seasonAutumn: "Autunno",
  seasonWinter: "Inverno",
  learnMore: "Scopri di più",
  viewEvent: "Vedi evento",
  viewGallery: "Vedi galleria",
  viewPoster: "Vedi la locandina",
  viewDetails: "Regolamento e dettagli",
  todayLabel: "Oggi",
  backToToday: "Torna al mese corrente",
  liveNow: "In corso ora",
  featured: "In evidenza",
  daysUnit: "giorni",
  countdownSuffix: "all’inizio",
  photosUnit: "foto",
  prevMonth: "Mese precedente",
  nextMonth: "Mese successivo",
  selectDay: "Seleziona una data per vederne gli eventi",
  emptyUpcoming: "Presto verranno annunciati nuovi eventi. Sfoglia quelli passati o torna più tardi.",
  emptyPast: "Ancora nessun evento passato. I primi ricordi devono ancora arrivare.",
  emptyMonth: "Nessun evento questo mese. Prova un altro mese.",
  emptyCategory: "Nessun evento in questa categoria. Rimuovi il filtro per vederli tutti.",
  clearFilter: "Rimuovi filtro",
  lightboxClose: "Chiudi",
};

const ro: EventsUiText = {
  viewCalendar: "Calendar",
  viewUpcoming: "Următoare",
  viewPast: "Trecute",
  tablistLabel: "Vizualizări evenimente",
  heroSubtitle:
    "Festivaluri, concursuri de fotografie, tradiții, aventuri și evenimente în natură — pe tot parcursul anului.",
  heroCta: "Explorează evenimentele",
  upcomingEyebrow: "Nu rata",
  upcomingTitle: "Evenimente următoare",
  pastEyebrow: "Arhivă",
  pastTitle: "Evenimente trecute",
  timelineEyebrow: "Pe tot parcursul anului",
  timelineTitle: "Un calendar al anotimpurilor",
  memoriesEyebrow: "Amintiri",
  memoriesTitle: "Amintiri din anii trecuți",
  filterAll: "Toate evenimentele",
  catTraditions: "Sărbători și tradiții",
  catChildren: "Evenimente pentru copii",
  catNature: "Natură și aventură",
  catContest: "Concursuri și expoziții",
  catCulture: "Cultură",
  seasonSpring: "Primăvară",
  seasonSummer: "Vară",
  seasonAutumn: "Toamnă",
  seasonWinter: "Iarnă",
  learnMore: "Află mai multe",
  viewEvent: "Vezi evenimentul",
  viewGallery: "Vezi galeria",
  viewPoster: "Vezi afișul",
  viewDetails: "Regulament și detalii",
  todayLabel: "Astăzi",
  backToToday: "Înapoi la luna curentă",
  liveNow: "Se întâmplă acum",
  featured: "Recomandat",
  daysUnit: "zile",
  countdownSuffix: "până la start",
  photosUnit: "fotografii",
  prevMonth: "Luna precedentă",
  nextMonth: "Luna următoare",
  selectDay: "Selectează o dată pentru a vedea evenimentele",
  emptyUpcoming: "Noi evenimente vor fi anunțate în curând. Răsfoiește-le pe cele trecute sau revino mai târziu.",
  emptyPast: "Încă nu există evenimente trecute. Primele amintiri urmează să vină.",
  emptyMonth: "Niciun eveniment în această lună. Încearcă altă lună.",
  emptyCategory: "Niciun eveniment în această categorie. Șterge filtrul pentru a le vedea pe toate.",
  clearFilter: "Șterge filtrul",
  lightboxClose: "Închide",
};

const tr: EventsUiText = {
  viewCalendar: "Takvim",
  viewUpcoming: "Yaklaşan",
  viewPast: "Geçmiş",
  tablistLabel: "Etkinlik görünümleri",
  heroSubtitle:
    "Festivaller, fotoğraf yarışmaları, gelenekler, maceralar ve doğada etkinlikler — yıl boyunca.",
  heroCta: "Etkinlikleri keşfet",
  upcomingEyebrow: "Kaçırma",
  upcomingTitle: "Yaklaşan etkinlikler",
  pastEyebrow: "Arşiv",
  pastTitle: "Geçmiş etkinlikler",
  timelineEyebrow: "Yıl boyunca",
  timelineTitle: "Mevsimler takvimi",
  memoriesEyebrow: "Anılar",
  memoriesTitle: "Geçmiş yıllardan anılar",
  filterAll: "Tüm etkinlikler",
  catTraditions: "Bayramlar ve gelenekler",
  catChildren: "Çocuk etkinlikleri",
  catNature: "Doğa ve macera",
  catContest: "Yarışmalar ve sergiler",
  catCulture: "Kültür",
  seasonSpring: "İlkbahar",
  seasonSummer: "Yaz",
  seasonAutumn: "Sonbahar",
  seasonWinter: "Kış",
  learnMore: "Daha fazla bilgi",
  viewEvent: "Etkinliği görüntüle",
  viewGallery: "Galeriyi görüntüle",
  viewPoster: "Afişi görüntüle",
  viewDetails: "Kurallar ve ayrıntılar",
  todayLabel: "Bugün",
  backToToday: "Geçerli aya dön",
  liveNow: "Şu anda gerçekleşiyor",
  featured: "Öne çıkan",
  daysUnit: "gün",
  countdownSuffix: "kaldı",
  photosUnit: "fotoğraf",
  prevMonth: "Önceki ay",
  nextMonth: "Sonraki ay",
  selectDay: "Etkinliklerini görmek için bir tarih seçin",
  emptyUpcoming: "Yeni etkinlikler yakında duyurulacak. Geçmiş etkinliklere göz atın veya daha sonra tekrar kontrol edin.",
  emptyPast: "Henüz geçmiş etkinlik yok. İlk anılar henüz gelmedi.",
  emptyMonth: "Bu ay etkinlik yok. Başka bir ay deneyin.",
  emptyCategory: "Bu kategoride etkinlik yok. Tümünü görmek için filtreyi temizleyin.",
  clearFilter: "Filtreyi temizle",
  lightboxClose: "Kapat",
};

const el: EventsUiText = {
  viewCalendar: "Ημερολόγιο",
  viewUpcoming: "Προσεχή",
  viewPast: "Παρελθόντα",
  tablistLabel: "Προβολές εκδηλώσεων",
  heroSubtitle:
    "Φεστιβάλ, διαγωνισμοί φωτογραφίας, παραδόσεις, περιπέτειες και εκδηλώσεις στη φύση — όλο τον χρόνο.",
  heroCta: "Εξερευνήστε τις εκδηλώσεις",
  upcomingEyebrow: "Μη χάσετε",
  upcomingTitle: "Προσεχείς εκδηλώσεις",
  pastEyebrow: "Αρχείο",
  pastTitle: "Παρελθούσες εκδηλώσεις",
  timelineEyebrow: "Όλο τον χρόνο",
  timelineTitle: "Ένα ημερολόγιο των εποχών",
  memoriesEyebrow: "Αναμνήσεις",
  memoriesTitle: "Αναμνήσεις από περασμένα χρόνια",
  filterAll: "Όλες οι εκδηλώσεις",
  catTraditions: "Γιορτές & παραδόσεις",
  catChildren: "Παιδικές εκδηλώσεις",
  catNature: "Φύση & περιπέτεια",
  catContest: "Διαγωνισμοί & εκθέσεις",
  catCulture: "Πολιτισμός",
  seasonSpring: "Άνοιξη",
  seasonSummer: "Καλοκαίρι",
  seasonAutumn: "Φθινόπωρο",
  seasonWinter: "Χειμώνας",
  learnMore: "Μάθετε περισσότερα",
  viewEvent: "Δείτε την εκδήλωση",
  viewGallery: "Δείτε τη συλλογή",
  viewPoster: "Δείτε την αφίσα",
  viewDetails: "Κανονισμός & λεπτομέρειες",
  todayLabel: "Σήμερα",
  backToToday: "Επιστροφή στον τρέχοντα μήνα",
  liveNow: "Συμβαίνει τώρα",
  featured: "Προβεβλημένο",
  daysUnit: "ημέρες",
  countdownSuffix: "μέχρι την έναρξη",
  photosUnit: "φωτογραφίες",
  prevMonth: "Προηγούμενος μήνας",
  nextMonth: "Επόμενος μήνας",
  selectDay: "Επιλέξτε μια ημερομηνία για να δείτε τις εκδηλώσεις της",
  emptyUpcoming: "Νέες εκδηλώσεις θα ανακοινωθούν σύντομα. Δείτε τις παλαιότερες ή επισκεφθείτε μας ξανά αργότερα.",
  emptyPast: "Δεν υπάρχουν ακόμη παρελθούσες εκδηλώσεις. Οι πρώτες αναμνήσεις είναι ακόμη μπροστά.",
  emptyMonth: "Δεν υπάρχουν εκδηλώσεις αυτόν τον μήνα. Δοκιμάστε άλλον μήνα.",
  emptyCategory: "Δεν υπάρχουν εκδηλώσεις σε αυτήν την κατηγορία. Καθαρίστε το φίλτρο για να τις δείτε όλες.",
  clearFilter: "Καθαρισμός φίλτρου",
  lightboxClose: "Κλείσιμο",
};

const ru: EventsUiText = {
  viewCalendar: "Календарь",
  viewUpcoming: "Предстоящие",
  viewPast: "Прошедшие",
  tablistLabel: "Виды событий",
  heroSubtitle:
    "Фестивали, фотоконкурсы, традиции, приключения и события на природе — круглый год.",
  heroCta: "Смотреть события",
  upcomingEyebrow: "Не пропустите",
  upcomingTitle: "Предстоящие события",
  pastEyebrow: "Архив",
  pastTitle: "Прошедшие события",
  timelineEyebrow: "Круглый год",
  timelineTitle: "Календарь сезонов",
  memoriesEyebrow: "Воспоминания",
  memoriesTitle: "Воспоминания прошлых лет",
  filterAll: "Все события",
  catTraditions: "Праздники и традиции",
  catChildren: "Детские события",
  catNature: "Природа и приключения",
  catContest: "Конкурсы и выставки",
  catCulture: "Культура",
  seasonSpring: "Весна",
  seasonSummer: "Лето",
  seasonAutumn: "Осень",
  seasonWinter: "Зима",
  learnMore: "Узнать больше",
  viewEvent: "Смотреть событие",
  viewGallery: "Смотреть галерею",
  viewPoster: "Смотреть афишу",
  viewDetails: "Правила и подробности",
  todayLabel: "Сегодня",
  backToToday: "К текущему месяцу",
  liveNow: "Происходит сейчас",
  featured: "Рекомендуем",
  daysUnit: "дней",
  countdownSuffix: "до старта",
  photosUnit: "фото",
  prevMonth: "Предыдущий месяц",
  nextMonth: "Следующий месяц",
  selectDay: "Выберите дату, чтобы увидеть события",
  emptyUpcoming: "Новые события скоро будут объявлены. Посмотрите прошедшие или зайдите позже.",
  emptyPast: "Прошедших событий пока нет. Первые воспоминания ещё впереди.",
  emptyMonth: "В этом месяце событий нет. Попробуйте другой месяц.",
  emptyCategory: "В этой категории событий нет. Очистите фильтр, чтобы увидеть все.",
  clearFilter: "Очистить фильтр",
  lightboxClose: "Закрыть",
};

const ja: EventsUiText = {
  viewCalendar: "カレンダー",
  viewUpcoming: "今後の予定",
  viewPast: "過去のイベント",
  tablistLabel: "イベント表示",
  heroSubtitle:
    "フェスティバル、写真コンテスト、伝統行事、アドベンチャー、そして自然の中でのイベントを一年を通して。",
  heroCta: "イベントを見る",
  upcomingEyebrow: "お見逃しなく",
  upcomingTitle: "今後のイベント",
  pastEyebrow: "アーカイブ",
  pastTitle: "過去のイベント",
  timelineEyebrow: "一年を通して",
  timelineTitle: "季節のカレンダー",
  memoriesEyebrow: "思い出",
  memoriesTitle: "過去の年の思い出",
  filterAll: "すべてのイベント",
  catTraditions: "祝祭と伝統",
  catChildren: "子ども向けイベント",
  catNature: "自然とアドベンチャー",
  catContest: "コンテストと展示会",
  catCulture: "文化",
  seasonSpring: "春",
  seasonSummer: "夏",
  seasonAutumn: "秋",
  seasonWinter: "冬",
  learnMore: "詳しく見る",
  viewEvent: "イベントを見る",
  viewGallery: "ギャラリーを見る",
  viewPoster: "ポスターを見る",
  viewDetails: "応募要項を見る",
  todayLabel: "今日",
  backToToday: "今月に戻る",
  liveNow: "開催中",
  featured: "注目",
  daysUnit: "日",
  countdownSuffix: "後",
  photosUnit: "枚",
  prevMonth: "前の月",
  nextMonth: "次の月",
  selectDay: "日付を選択してイベントを表示",
  emptyUpcoming: "新しいイベントは近日発表されます。過去のイベントをご覧いただくか、後ほど再度ご確認ください。",
  emptyPast: "過去のイベントはまだありません。最初の思い出はこれからです。",
  emptyMonth: "今月はイベントがありません。別の月をお試しください。",
  emptyCategory: "このカテゴリーにイベントはありません。フィルターを解除してすべて表示してください。",
  clearFilter: "フィルターを解除",
  lightboxClose: "閉じる",
};

const sr: EventsUiText = {
  viewCalendar: "Календар",
  viewUpcoming: "Предстојећи",
  viewPast: "Прошли",
  tablistLabel: "Прикази догађаја",
  heroSubtitle:
    "Фестивали, фотографски конкурси, традиције, авантуре и догађаји у природи — током целе године.",
  heroCta: "Истражите догађаје",
  upcomingEyebrow: "Не пропустите",
  upcomingTitle: "Предстојећи догађаји",
  pastEyebrow: "Архива",
  pastTitle: "Прошли догађаји",
  timelineEyebrow: "Током целе године",
  timelineTitle: "Календар годишњих доба",
  memoriesEyebrow: "Успомене",
  memoriesTitle: "Успомене из претходних година",
  filterAll: "Сви догађаји",
  catTraditions: "Празници и традиције",
  catChildren: "Дечји догађаји",
  catNature: "Природа и авантура",
  catContest: "Конкурси и изложбе",
  catCulture: "Култура",
  seasonSpring: "Пролеће",
  seasonSummer: "Лето",
  seasonAutumn: "Јесен",
  seasonWinter: "Зима",
  learnMore: "Сазнајте више",
  viewEvent: "Погледајте догађај",
  viewGallery: "Погледајте галерију",
  viewPoster: "Погледајте плакат",
  viewDetails: "Правила и детаљи",
  todayLabel: "Данас",
  backToToday: "Назад на текући месец",
  liveNow: "Дешава се сада",
  featured: "Издвојено",
  daysUnit: "дана",
  countdownSuffix: "до почетка",
  photosUnit: "фотографија",
  prevMonth: "Претходни месец",
  nextMonth: "Следећи месец",
  selectDay: "Изаберите датум да видите његове догађаје",
  emptyUpcoming: "Нови догађаји биће ускоро најављени. Прегледајте прошле или се вратите касније.",
  emptyPast: "Још нема прошлих догађаја. Прве успомене тек долазе.",
  emptyMonth: "Нема догађаја овог месеца. Покушајте други месец.",
  emptyCategory: "Нема догађаја у овој категорији. Обришите филтер да видите све.",
  clearFilter: "Обриши филтер",
  lightboxClose: "Затвори",
};

const zh: EventsUiText = {
  viewCalendar: "日历",
  viewUpcoming: "即将举办",
  viewPast: "往期",
  tablistLabel: "活动视图",
  heroSubtitle:
    "节庆、摄影比赛、传统习俗、探险以及大自然中的各类活动——全年不断。",
  heroCta: "探索活动",
  upcomingEyebrow: "不容错过",
  upcomingTitle: "即将举办的活动",
  pastEyebrow: "档案",
  pastTitle: "往期活动",
  timelineEyebrow: "全年不断",
  timelineTitle: "四季日历",
  memoriesEyebrow: "回忆",
  memoriesTitle: "往年回忆",
  filterAll: "全部活动",
  catTraditions: "节日与传统",
  catChildren: "儿童活动",
  catNature: "自然与探险",
  catContest: "比赛与展览",
  catCulture: "文化",
  seasonSpring: "春季",
  seasonSummer: "夏季",
  seasonAutumn: "秋季",
  seasonWinter: "冬季",
  learnMore: "了解更多",
  viewEvent: "查看活动",
  viewGallery: "查看图库",
  viewPoster: "查看海报",
  viewDetails: "规则与详情",
  todayLabel: "今天",
  backToToday: "返回当前月份",
  liveNow: "正在进行",
  featured: "精选",
  daysUnit: "天",
  countdownSuffix: "后",
  photosUnit: "张照片",
  prevMonth: "上个月",
  nextMonth: "下个月",
  selectDay: "选择日期以查看当日活动",
  emptyUpcoming: "新活动即将公布。请浏览往期活动或稍后再来查看。",
  emptyPast: "暂无往期活动。最初的回忆尚未到来。",
  emptyMonth: "本月没有活动。请尝试其他月份。",
  emptyCategory: "此类别下暂无活动。清除筛选以查看全部。",
  clearFilter: "清除筛选",
  lightboxClose: "关闭",
};

const hu: EventsUiText = {
  viewCalendar: "Naptár",
  viewUpcoming: "Közelgő",
  viewPast: "Korábbi",
  tablistLabel: "Eseménynézetek",
  heroSubtitle:
    "Fesztiválok, fotópályázatok, hagyományok, kalandok és események a természetben — egész évben.",
  heroCta: "Fedezze fel az eseményeket",
  upcomingEyebrow: "Ne hagyja ki",
  upcomingTitle: "Közelgő események",
  pastEyebrow: "Archívum",
  pastTitle: "Korábbi események",
  timelineEyebrow: "Egész évben",
  timelineTitle: "Az évszakok naptára",
  memoriesEyebrow: "Emlékek",
  memoriesTitle: "Emlékek az elmúlt évekből",
  filterAll: "Minden esemény",
  catTraditions: "Ünnepek és hagyományok",
  catChildren: "Gyermekprogramok",
  catNature: "Természet és kaland",
  catContest: "Versenyek és kiállítások",
  catCulture: "Kultúra",
  seasonSpring: "Tavasz",
  seasonSummer: "Nyár",
  seasonAutumn: "Ősz",
  seasonWinter: "Tél",
  learnMore: "Tudjon meg többet",
  viewEvent: "Esemény megtekintése",
  viewGallery: "Galéria megtekintése",
  viewPoster: "Plakát megtekintése",
  viewDetails: "Szabályzat és részletek",
  todayLabel: "Ma",
  backToToday: "Vissza az aktuális hónaphoz",
  liveNow: "Éppen zajlik",
  featured: "Kiemelt",
  daysUnit: "nap",
  countdownSuffix: "van hátra",
  photosUnit: "fénykép",
  prevMonth: "Előző hónap",
  nextMonth: "Következő hónap",
  selectDay: "Válasszon egy dátumot az események megtekintéséhez",
  emptyUpcoming: "Hamarosan új eseményeket jelentünk be. Böngésszen a korábbiak között, vagy nézzen vissza később.",
  emptyPast: "Még nincsenek korábbi események. Az első emlékek még csak ezután jönnek.",
  emptyMonth: "Ebben a hónapban nincsenek események. Próbáljon másik hónapot.",
  emptyCategory: "Nincsenek események ebben a kategóriában. Törölje a szűrőt, hogy mindet lássa.",
  clearFilter: "Szűrő törlése",
  lightboxClose: "Bezárás",
};

export const eventsUiByLanguage: Record<LanguageCode, EventsUiText> = {
  bg,
  en,
  de,
  fr,
  es,
  it,
  ro,
  tr,
  el,
  ru,
  ja,
  sr,
  zh,
  hu,
};

export const categoryOrder: EventCategory[] = ["traditions", "children", "nature", "contest", "culture"];

export function categoryLabel(ui: EventsUiText, category: EventCategory): string {
  switch (category) {
    case "traditions":
      return ui.catTraditions;
    case "children":
      return ui.catChildren;
    case "nature":
      return ui.catNature;
    case "contest":
      return ui.catContest;
    case "culture":
      return ui.catCulture;
  }
}

export const seasonOrder: EventSeason[] = ["spring", "summer", "autumn", "winter"];

export function seasonLabel(ui: EventsUiText, season: EventSeason): string {
  switch (season) {
    case "spring":
      return ui.seasonSpring;
    case "summer":
      return ui.seasonSummer;
    case "autumn":
      return ui.seasonAutumn;
    case "winter":
      return ui.seasonWinter;
  }
}

export const seasonEmoji: Record<EventSeason, string> = {
  spring: "🌸",
  summer: "🌞",
  autumn: "🍂",
  winter: "❄️",
};
