import type { BusinessCategory, LanguageCode } from "./locales/types";

// UI strings for the local businesses page. Weekday and date names come from
// Intl.DateTimeFormat(locale); only these labels are translated here.
export type BusinessesUiText = {
  // Hero
  heroEyebrow: string;
  heroTitle: string;
  heroSubtitle: string;
  heroTagline: string;
  heroCtaExplore: string;
  heroCtaAdd: string;
  // Search + filters
  searchLabel: string;
  searchPlaceholder: string;
  filtersAria: string;
  categoriesAria: string;
  filterAll: string;
  filterOpenNow: string;
  filterDelivery: string;
  filterPickup: string;
  clearFilters: string;
  resultsCount: string; // "{count}" is replaced with the number of results
  // Categories
  catFood: string;
  catShops: string;
  catProducers: string;
  catStay: string;
  catCrafts: string;
  catServices: string;
  catFarming: string;
  catOther: string;
  // Sections
  featuredEyebrow: string;
  featuredTitle: string;
  featuredBadge: string;
  listTitle: string;
  storiesEyebrow: string;
  storiesTitle: string;
  productsEyebrow: string;
  productsTitle: string;
  productsNote: string;
  addEyebrow: string;
  addTitle: string;
  addText: string;
  addCta: string;
  addReviewNote: string;
  addContactIntro: string;
  // Cards + detail
  viewDetails: string;
  call: string;
  openMap: string;
  visitWebsite: string;
  sendEmail: string;
  backToList: string;
  detailAbout: string;
  detailProducts: string;
  detailServices: string;
  detailContact: string;
  detailHours: string;
  detailLocation: string;
  detailGallery: string;
  detailAccessibility: string;
  detailStory: string;
  detailRelated: string;
  reportIssue: string;
  lastUpdated: string;
  closedDay: string;
  // Badges / status
  badgeDelivery: string;
  badgePickup: string;
  badgeBooking: string;
  badgeSeasonal: string;
  badgeVerified: string;
  badgeOpenNow: string;
  badgeClosedNow: string;
  badgeTemporarilyClosed: string;
  // Empty states
  emptyAll: string;
  emptyCategory: string;
  emptyResults: string;
  notFound: string;
};

const bg: BusinessesUiText = {
  heroEyebrow: "Пазарувай местно",
  heroTitle: "Местен бизнес в Ъглен",
  heroSubtitle: "Открийте местните магазини, производители, услуги и хората, които дават живот на селото.",
  heroTagline: "Пазарувай местно. Опознай хората зад Ъглен.",
  heroCtaExplore: "Разгледай местата",
  heroCtaAdd: "Добави своя бизнес",
  searchLabel: "Търсене на местен бизнес",
  searchPlaceholder: "Търси магазин, услуга или местен продукт…",
  filtersAria: "Допълнителни филтри",
  categoriesAria: "Категории",
  filterAll: "Всички",
  filterOpenNow: "Отворено сега",
  filterDelivery: "С доставка",
  filterPickup: "Взимане на място",
  clearFilters: "Изчисти филтрите",
  resultsCount: "Показани места: {count}",
  catFood: "Храна и напитки",
  catShops: "Магазини",
  catProducers: "Местни производители",
  catStay: "Настаняване",
  catCrafts: "Занаяти и изкуство",
  catServices: "Услуги",
  catFarming: "Земеделие",
  catOther: "Други",
  featuredEyebrow: "Избрано от общността",
  featuredTitle: "Препоръчани местни места",
  featuredBadge: "Представено място",
  listTitle: "Местата в Ъглен",
  storiesEyebrow: "Истории",
  storiesTitle: "Хората зад Ъглен",
  productsEyebrow: "Местни продукти",
  productsTitle: "Произведено в Ъглен",
  productsNote: "Разгледайте кой предлага какво — и се свържете директно с производителя.",
  addEyebrow: "За местните",
  addTitle: "Имате бизнес в Ъглен?",
  addText:
    "Представете своя магазин, услуга, земеделско стопанство или местен продукт пред жителите и гостите на селото.",
  addCta: "Добави своя бизнес",
  addReviewNote: "Всяка заявка се преглежда преди публикуване.",
  addContactIntro: "Изпратете информацията на:",
  viewDetails: "Виж подробности",
  call: "Обади се",
  openMap: "Отвори карта",
  visitWebsite: "Посети сайта",
  sendEmail: "Изпрати имейл",
  backToList: "Към всички места",
  detailAbout: "За мястото",
  detailProducts: "Продукти",
  detailServices: "Услуги",
  detailContact: "Контакти",
  detailHours: "Работно време",
  detailLocation: "Къде се намира",
  detailGallery: "Галерия",
  detailAccessibility: "Достъпност",
  detailStory: "Историята",
  detailRelated: "Наблизо в Ъглен",
  reportIssue: "Съобщи за неточна информация",
  lastUpdated: "Обновено на",
  closedDay: "Затворено",
  badgeDelivery: "Доставка",
  badgePickup: "Взимане на място",
  badgeBooking: "Със запазване",
  badgeSeasonal: "Сезонно",
  badgeVerified: "Потвърдено",
  badgeOpenNow: "Отворено сега",
  badgeClosedNow: "Затворено сега",
  badgeTemporarilyClosed: "Временно затворено",
  emptyAll: "Все още няма добавени места. Ако имате бизнес в Ъглен, представете го тук.",
  emptyCategory: "Все още няма добавени места в тази категория. Опитайте друга категория или предложете местен бизнес.",
  emptyResults: "Няма съвпадения за това търсене. Опитайте с друга дума или изчистете филтрите.",
  notFound: "Това място не беше намерено. Вижте всички местни бизнеси.",
};

const en: BusinessesUiText = {
  heroEyebrow: "Shop local",
  heroTitle: "Local business in Aglen",
  heroSubtitle: "Discover the local shops, producers, services and the people who bring the village to life.",
  heroTagline: "Shop local. Meet the people behind Aglen.",
  heroCtaExplore: "Browse the places",
  heroCtaAdd: "Add your business",
  searchLabel: "Search local businesses",
  searchPlaceholder: "Search for a shop, a service or a local product…",
  filtersAria: "Additional filters",
  categoriesAria: "Categories",
  filterAll: "All",
  filterOpenNow: "Open now",
  filterDelivery: "Delivery",
  filterPickup: "Pickup",
  clearFilters: "Clear filters",
  resultsCount: "Showing {count} places",
  catFood: "Food & drink",
  catShops: "Shops",
  catProducers: "Local producers",
  catStay: "Places to stay",
  catCrafts: "Crafts & art",
  catServices: "Services",
  catFarming: "Farming",
  catOther: "Other",
  featuredEyebrow: "Chosen by the community",
  featuredTitle: "Featured local places",
  featuredBadge: "Featured place",
  listTitle: "Places in Aglen",
  storiesEyebrow: "Stories",
  storiesTitle: "The people behind Aglen",
  productsEyebrow: "Local products",
  productsTitle: "Made in Aglen",
  productsNote: "See who offers what — and get in touch with the producer directly.",
  addEyebrow: "For locals",
  addTitle: "Do you run a business in Aglen?",
  addText:
    "Present your shop, service, farm or local product to the residents and the guests of the village.",
  addCta: "Add your business",
  addReviewNote: "Every submission is reviewed before it is published.",
  addContactIntro: "Send your details to:",
  viewDetails: "View details",
  call: "Call",
  openMap: "Open map",
  visitWebsite: "Visit website",
  sendEmail: "Send email",
  backToList: "Back to all places",
  detailAbout: "About",
  detailProducts: "Products",
  detailServices: "Services",
  detailContact: "Contact",
  detailHours: "Opening hours",
  detailLocation: "Where to find it",
  detailGallery: "Gallery",
  detailAccessibility: "Accessibility",
  detailStory: "The story",
  detailRelated: "Nearby in Aglen",
  reportIssue: "Report incorrect information",
  lastUpdated: "Updated on",
  closedDay: "Closed",
  badgeDelivery: "Delivery",
  badgePickup: "Pickup",
  badgeBooking: "Booking required",
  badgeSeasonal: "Seasonal",
  badgeVerified: "Verified",
  badgeOpenNow: "Open now",
  badgeClosedNow: "Closed now",
  badgeTemporarilyClosed: "Temporarily closed",
  emptyAll: "No places have been added yet. If you run a business in Aglen, present it here.",
  emptyCategory: "No places in this category yet. Try another category or suggest a local business.",
  emptyResults: "Nothing matches this search. Try another word or clear the filters.",
  notFound: "This place could not be found. See all local businesses.",
};

const de: BusinessesUiText = {
  heroEyebrow: "Lokal einkaufen",
  heroTitle: "Lokale Betriebe in Aglen",
  heroSubtitle: "Entdecken Sie die Läden, Erzeuger, Dienstleistungen und die Menschen, die das Dorf lebendig machen.",
  heroTagline: "Lokal einkaufen. Die Menschen hinter Aglen kennenlernen.",
  heroCtaExplore: "Orte entdecken",
  heroCtaAdd: "Betrieb eintragen",
  searchLabel: "Lokale Betriebe suchen",
  searchPlaceholder: "Laden, Dienstleistung oder lokales Produkt suchen…",
  filtersAria: "Weitere Filter",
  categoriesAria: "Kategorien",
  filterAll: "Alle",
  filterOpenNow: "Jetzt geöffnet",
  filterDelivery: "Lieferung",
  filterPickup: "Abholung",
  clearFilters: "Filter entfernen",
  resultsCount: "{count} Orte angezeigt",
  catFood: "Essen & Trinken",
  catShops: "Geschäfte",
  catProducers: "Lokale Erzeuger",
  catStay: "Unterkünfte",
  catCrafts: "Handwerk & Kunst",
  catServices: "Dienstleistungen",
  catFarming: "Landwirtschaft",
  catOther: "Sonstiges",
  featuredEyebrow: "Von der Gemeinschaft ausgewählt",
  featuredTitle: "Empfohlene lokale Orte",
  featuredBadge: "Vorgestellter Ort",
  listTitle: "Orte in Aglen",
  storiesEyebrow: "Geschichten",
  storiesTitle: "Die Menschen hinter Aglen",
  productsEyebrow: "Lokale Produkte",
  productsTitle: "Hergestellt in Aglen",
  productsNote: "Sehen Sie, wer was anbietet — und wenden Sie sich direkt an den Erzeuger.",
  addEyebrow: "Für Einheimische",
  addTitle: "Haben Sie einen Betrieb in Aglen?",
  addText:
    "Stellen Sie Ihren Laden, Ihre Dienstleistung, Ihren Hof oder Ihr lokales Produkt den Bewohnern und Gästen des Dorfes vor.",
  addCta: "Betrieb eintragen",
  addReviewNote: "Jede Einsendung wird vor der Veröffentlichung geprüft.",
  addContactIntro: "Senden Sie Ihre Angaben an:",
  viewDetails: "Details ansehen",
  call: "Anrufen",
  openMap: "Karte öffnen",
  visitWebsite: "Website besuchen",
  sendEmail: "E-Mail senden",
  backToList: "Zurück zu allen Orten",
  detailAbout: "Über den Betrieb",
  detailProducts: "Produkte",
  detailServices: "Leistungen",
  detailContact: "Kontakt",
  detailHours: "Öffnungszeiten",
  detailLocation: "So finden Sie uns",
  detailGallery: "Galerie",
  detailAccessibility: "Barrierefreiheit",
  detailStory: "Die Geschichte",
  detailRelated: "In der Nähe in Aglen",
  reportIssue: "Falsche Angaben melden",
  lastUpdated: "Aktualisiert am",
  closedDay: "Geschlossen",
  badgeDelivery: "Lieferung",
  badgePickup: "Abholung",
  badgeBooking: "Reservierung nötig",
  badgeSeasonal: "Saisonal",
  badgeVerified: "Bestätigt",
  badgeOpenNow: "Jetzt geöffnet",
  badgeClosedNow: "Jetzt geschlossen",
  badgeTemporarilyClosed: "Vorübergehend geschlossen",
  emptyAll: "Es wurden noch keine Orte hinzugefügt. Wenn Sie einen Betrieb in Aglen führen, stellen Sie ihn hier vor.",
  emptyCategory: "In dieser Kategorie gibt es noch keine Orte. Versuchen Sie eine andere Kategorie oder schlagen Sie einen Betrieb vor.",
  emptyResults: "Keine Treffer für diese Suche. Versuchen Sie ein anderes Wort oder entfernen Sie die Filter.",
  notFound: "Dieser Ort wurde nicht gefunden. Sehen Sie alle lokalen Betriebe.",
};

const fr: BusinessesUiText = {
  heroEyebrow: "Achetez local",
  heroTitle: "Commerces locaux à Aglen",
  heroSubtitle: "Découvrez les commerces, les producteurs, les services et les personnes qui font vivre le village.",
  heroTagline: "Achetez local. Rencontrez les gens derrière Aglen.",
  heroCtaExplore: "Parcourir les lieux",
  heroCtaAdd: "Ajouter votre activité",
  searchLabel: "Rechercher un commerce local",
  searchPlaceholder: "Cherchez un commerce, un service ou un produit local…",
  filtersAria: "Filtres supplémentaires",
  categoriesAria: "Catégories",
  filterAll: "Tous",
  filterOpenNow: "Ouvert maintenant",
  filterDelivery: "Livraison",
  filterPickup: "Retrait sur place",
  clearFilters: "Effacer les filtres",
  resultsCount: "{count} lieux affichés",
  catFood: "Manger & boire",
  catShops: "Commerces",
  catProducers: "Producteurs locaux",
  catStay: "Hébergements",
  catCrafts: "Artisanat & art",
  catServices: "Services",
  catFarming: "Agriculture",
  catOther: "Autres",
  featuredEyebrow: "Choisi par la communauté",
  featuredTitle: "Lieux locaux à découvrir",
  featuredBadge: "Lieu mis en avant",
  listTitle: "Les lieux d’Aglen",
  storiesEyebrow: "Récits",
  storiesTitle: "Les gens derrière Aglen",
  productsEyebrow: "Produits locaux",
  productsTitle: "Fabriqué à Aglen",
  productsNote: "Voyez qui propose quoi — et contactez directement le producteur.",
  addEyebrow: "Pour les habitants",
  addTitle: "Vous avez une activité à Aglen ?",
  addText:
    "Présentez votre commerce, votre service, votre ferme ou votre produit local aux habitants et aux visiteurs du village.",
  addCta: "Ajouter votre activité",
  addReviewNote: "Chaque demande est vérifiée avant publication.",
  addContactIntro: "Envoyez vos informations à :",
  viewDetails: "Voir les détails",
  call: "Appeler",
  openMap: "Ouvrir la carte",
  visitWebsite: "Visiter le site",
  sendEmail: "Envoyer un e-mail",
  backToList: "Retour à tous les lieux",
  detailAbout: "À propos",
  detailProducts: "Produits",
  detailServices: "Services",
  detailContact: "Contact",
  detailHours: "Horaires",
  detailLocation: "Où le trouver",
  detailGallery: "Galerie",
  detailAccessibility: "Accessibilité",
  detailStory: "L’histoire",
  detailRelated: "À proximité à Aglen",
  reportIssue: "Signaler une information incorrecte",
  lastUpdated: "Mis à jour le",
  closedDay: "Fermé",
  badgeDelivery: "Livraison",
  badgePickup: "Retrait",
  badgeBooking: "Réservation requise",
  badgeSeasonal: "Saisonnier",
  badgeVerified: "Vérifié",
  badgeOpenNow: "Ouvert maintenant",
  badgeClosedNow: "Fermé actuellement",
  badgeTemporarilyClosed: "Temporairement fermé",
  emptyAll: "Aucun lieu n’a encore été ajouté. Si vous avez une activité à Aglen, présentez-la ici.",
  emptyCategory: "Aucun lieu dans cette catégorie pour l’instant. Essayez une autre catégorie ou proposez un commerce local.",
  emptyResults: "Aucun résultat pour cette recherche. Essayez un autre mot ou effacez les filtres.",
  notFound: "Ce lieu est introuvable. Voir tous les commerces locaux.",
};

const es: BusinessesUiText = {
  heroEyebrow: "Compra local",
  heroTitle: "Negocios locales en Aglen",
  heroSubtitle: "Descubre las tiendas, los productores, los servicios y las personas que dan vida al pueblo.",
  heroTagline: "Compra local. Conoce a la gente detrás de Aglen.",
  heroCtaExplore: "Explorar los lugares",
  heroCtaAdd: "Añade tu negocio",
  searchLabel: "Buscar negocios locales",
  searchPlaceholder: "Busca una tienda, un servicio o un producto local…",
  filtersAria: "Filtros adicionales",
  categoriesAria: "Categorías",
  filterAll: "Todos",
  filterOpenNow: "Abierto ahora",
  filterDelivery: "Con entrega",
  filterPickup: "Recogida",
  clearFilters: "Borrar filtros",
  resultsCount: "Mostrando {count} lugares",
  catFood: "Comida y bebida",
  catShops: "Tiendas",
  catProducers: "Productores locales",
  catStay: "Alojamiento",
  catCrafts: "Artesanía y arte",
  catServices: "Servicios",
  catFarming: "Agricultura",
  catOther: "Otros",
  featuredEyebrow: "Elegido por la comunidad",
  featuredTitle: "Lugares locales destacados",
  featuredBadge: "Lugar destacado",
  listTitle: "Lugares de Aglen",
  storiesEyebrow: "Historias",
  storiesTitle: "La gente detrás de Aglen",
  productsEyebrow: "Productos locales",
  productsTitle: "Hecho en Aglen",
  productsNote: "Mira quién ofrece qué y ponte en contacto directamente con el productor.",
  addEyebrow: "Para los vecinos",
  addTitle: "¿Tienes un negocio en Aglen?",
  addText:
    "Presenta tu tienda, tu servicio, tu explotación agrícola o tu producto local a los vecinos y visitantes del pueblo.",
  addCta: "Añade tu negocio",
  addReviewNote: "Cada solicitud se revisa antes de publicarse.",
  addContactIntro: "Envía tus datos a:",
  viewDetails: "Ver detalles",
  call: "Llamar",
  openMap: "Abrir mapa",
  visitWebsite: "Visitar la web",
  sendEmail: "Enviar correo",
  backToList: "Volver a todos los lugares",
  detailAbout: "Sobre el negocio",
  detailProducts: "Productos",
  detailServices: "Servicios",
  detailContact: "Contacto",
  detailHours: "Horario",
  detailLocation: "Dónde encontrarlo",
  detailGallery: "Galería",
  detailAccessibility: "Accesibilidad",
  detailStory: "La historia",
  detailRelated: "Cerca en Aglen",
  reportIssue: "Informar de datos incorrectos",
  lastUpdated: "Actualizado el",
  closedDay: "Cerrado",
  badgeDelivery: "Entrega",
  badgePickup: "Recogida",
  badgeBooking: "Con reserva",
  badgeSeasonal: "De temporada",
  badgeVerified: "Verificado",
  badgeOpenNow: "Abierto ahora",
  badgeClosedNow: "Cerrado ahora",
  badgeTemporarilyClosed: "Cerrado temporalmente",
  emptyAll: "Todavía no se ha añadido ningún lugar. Si tienes un negocio en Aglen, preséntalo aquí.",
  emptyCategory: "Aún no hay lugares en esta categoría. Prueba otra categoría o propón un negocio local.",
  emptyResults: "No hay resultados para esta búsqueda. Prueba otra palabra o borra los filtros.",
  notFound: "No se ha encontrado este lugar. Ver todos los negocios locales.",
};

const it: BusinessesUiText = {
  heroEyebrow: "Compra locale",
  heroTitle: "Attività locali ad Aglen",
  heroSubtitle: "Scopri i negozi, i produttori, i servizi e le persone che danno vita al villaggio.",
  heroTagline: "Compra locale. Conosci le persone dietro Aglen.",
  heroCtaExplore: "Esplora i luoghi",
  heroCtaAdd: "Aggiungi la tua attività",
  searchLabel: "Cerca attività locali",
  searchPlaceholder: "Cerca un negozio, un servizio o un prodotto locale…",
  filtersAria: "Filtri aggiuntivi",
  categoriesAria: "Categorie",
  filterAll: "Tutte",
  filterOpenNow: "Aperto ora",
  filterDelivery: "Consegna",
  filterPickup: "Ritiro sul posto",
  clearFilters: "Rimuovi filtri",
  resultsCount: "{count} luoghi mostrati",
  catFood: "Cibo e bevande",
  catShops: "Negozi",
  catProducers: "Produttori locali",
  catStay: "Alloggi",
  catCrafts: "Artigianato e arte",
  catServices: "Servizi",
  catFarming: "Agricoltura",
  catOther: "Altro",
  featuredEyebrow: "Scelto dalla comunità",
  featuredTitle: "Luoghi locali in evidenza",
  featuredBadge: "Luogo in evidenza",
  listTitle: "I luoghi di Aglen",
  storiesEyebrow: "Storie",
  storiesTitle: "Le persone dietro Aglen",
  productsEyebrow: "Prodotti locali",
  productsTitle: "Fatto ad Aglen",
  productsNote: "Scopri chi offre cosa e contatta direttamente il produttore.",
  addEyebrow: "Per gli abitanti",
  addTitle: "Hai un’attività ad Aglen?",
  addText:
    "Presenta il tuo negozio, il tuo servizio, la tua azienda agricola o il tuo prodotto locale agli abitanti e agli ospiti del villaggio.",
  addCta: "Aggiungi la tua attività",
  addReviewNote: "Ogni richiesta viene verificata prima della pubblicazione.",
  addContactIntro: "Invia i tuoi dati a:",
  viewDetails: "Vedi dettagli",
  call: "Chiama",
  openMap: "Apri la mappa",
  visitWebsite: "Visita il sito",
  sendEmail: "Invia email",
  backToList: "Torna a tutti i luoghi",
  detailAbout: "Informazioni",
  detailProducts: "Prodotti",
  detailServices: "Servizi",
  detailContact: "Contatti",
  detailHours: "Orari",
  detailLocation: "Dove si trova",
  detailGallery: "Galleria",
  detailAccessibility: "Accessibilità",
  detailStory: "La storia",
  detailRelated: "Nelle vicinanze ad Aglen",
  reportIssue: "Segnala informazioni errate",
  lastUpdated: "Aggiornato il",
  closedDay: "Chiuso",
  badgeDelivery: "Consegna",
  badgePickup: "Ritiro",
  badgeBooking: "Su prenotazione",
  badgeSeasonal: "Stagionale",
  badgeVerified: "Verificato",
  badgeOpenNow: "Aperto ora",
  badgeClosedNow: "Chiuso ora",
  badgeTemporarilyClosed: "Temporaneamente chiuso",
  emptyAll: "Non è ancora stato aggiunto nessun luogo. Se hai un’attività ad Aglen, presentala qui.",
  emptyCategory: "Ancora nessun luogo in questa categoria. Prova un’altra categoria o proponi un’attività locale.",
  emptyResults: "Nessun risultato per questa ricerca. Prova un’altra parola o rimuovi i filtri.",
  notFound: "Questo luogo non è stato trovato. Vedi tutte le attività locali.",
};

const ro: BusinessesUiText = {
  heroEyebrow: "Cumpără local",
  heroTitle: "Afaceri locale în Aglen",
  heroSubtitle: "Descoperiți magazinele, producătorii, serviciile și oamenii care dau viață satului.",
  heroTagline: "Cumpără local. Cunoaște oamenii din spatele Aglenului.",
  heroCtaExplore: "Explorează locurile",
  heroCtaAdd: "Adaugă-ți afacerea",
  searchLabel: "Caută afaceri locale",
  searchPlaceholder: "Caută un magazin, un serviciu sau un produs local…",
  filtersAria: "Filtre suplimentare",
  categoriesAria: "Categorii",
  filterAll: "Toate",
  filterOpenNow: "Deschis acum",
  filterDelivery: "Cu livrare",
  filterPickup: "Ridicare personală",
  clearFilters: "Șterge filtrele",
  resultsCount: "{count} locuri afișate",
  catFood: "Mâncare și băutură",
  catShops: "Magazine",
  catProducers: "Producători locali",
  catStay: "Cazare",
  catCrafts: "Meșteșuguri și artă",
  catServices: "Servicii",
  catFarming: "Agricultură",
  catOther: "Altele",
  featuredEyebrow: "Ales de comunitate",
  featuredTitle: "Locuri locale recomandate",
  featuredBadge: "Loc prezentat",
  listTitle: "Locurile din Aglen",
  storiesEyebrow: "Povești",
  storiesTitle: "Oamenii din spatele Aglenului",
  productsEyebrow: "Produse locale",
  productsTitle: "Produs în Aglen",
  productsNote: "Vedeți cine ce oferă și contactați direct producătorul.",
  addEyebrow: "Pentru localnici",
  addTitle: "Aveți o afacere în Aglen?",
  addText:
    "Prezentați-vă magazinul, serviciul, ferma sau produsul local locuitorilor și oaspeților satului.",
  addCta: "Adaugă-ți afacerea",
  addReviewNote: "Fiecare solicitare este verificată înainte de publicare.",
  addContactIntro: "Trimiteți datele la:",
  viewDetails: "Vezi detalii",
  call: "Sună",
  openMap: "Deschide harta",
  visitWebsite: "Vizitează site-ul",
  sendEmail: "Trimite e-mail",
  backToList: "Înapoi la toate locurile",
  detailAbout: "Despre",
  detailProducts: "Produse",
  detailServices: "Servicii",
  detailContact: "Contact",
  detailHours: "Program",
  detailLocation: "Unde se află",
  detailGallery: "Galerie",
  detailAccessibility: "Accesibilitate",
  detailStory: "Povestea",
  detailRelated: "În apropiere în Aglen",
  reportIssue: "Raportează informații incorecte",
  lastUpdated: "Actualizat la",
  closedDay: "Închis",
  badgeDelivery: "Livrare",
  badgePickup: "Ridicare",
  badgeBooking: "Cu rezervare",
  badgeSeasonal: "Sezonier",
  badgeVerified: "Verificat",
  badgeOpenNow: "Deschis acum",
  badgeClosedNow: "Închis acum",
  badgeTemporarilyClosed: "Închis temporar",
  emptyAll: "Încă nu au fost adăugate locuri. Dacă aveți o afacere în Aglen, prezentați-o aici.",
  emptyCategory: "Încă nu există locuri în această categorie. Încercați altă categorie sau propuneți o afacere locală.",
  emptyResults: "Nicio potrivire pentru această căutare. Încercați alt cuvânt sau ștergeți filtrele.",
  notFound: "Acest loc nu a fost găsit. Vedeți toate afacerile locale.",
};

const tr: BusinessesUiText = {
  heroEyebrow: "Yerelden alışveriş",
  heroTitle: "Aglen’de yerel işletmeler",
  heroSubtitle: "Köye hayat veren dükkânları, üreticileri, hizmetleri ve insanları keşfedin.",
  heroTagline: "Yerelden alışveriş yap. Aglen’in arkasındaki insanları tanı.",
  heroCtaExplore: "Yerleri keşfet",
  heroCtaAdd: "İşletmeni ekle",
  searchLabel: "Yerel işletme ara",
  searchPlaceholder: "Dükkân, hizmet veya yerel ürün ara…",
  filtersAria: "Ek filtreler",
  categoriesAria: "Kategoriler",
  filterAll: "Tümü",
  filterOpenNow: "Şu anda açık",
  filterDelivery: "Teslimat",
  filterPickup: "Yerinden alım",
  clearFilters: "Filtreleri temizle",
  resultsCount: "{count} yer gösteriliyor",
  catFood: "Yeme & içme",
  catShops: "Dükkânlar",
  catProducers: "Yerel üreticiler",
  catStay: "Konaklama",
  catCrafts: "El sanatları & sanat",
  catServices: "Hizmetler",
  catFarming: "Tarım",
  catOther: "Diğer",
  featuredEyebrow: "Toplulukça seçildi",
  featuredTitle: "Öne çıkan yerel yerler",
  featuredBadge: "Öne çıkan yer",
  listTitle: "Aglen’deki yerler",
  storiesEyebrow: "Hikâyeler",
  storiesTitle: "Aglen’in arkasındaki insanlar",
  productsEyebrow: "Yerel ürünler",
  productsTitle: "Aglen’de üretildi",
  productsNote: "Kimin ne sunduğunu görün ve doğrudan üreticiyle iletişime geçin.",
  addEyebrow: "Yerel halka",
  addTitle: "Aglen’de bir işletmeniz mi var?",
  addText:
    "Dükkânınızı, hizmetinizi, çiftliğinizi veya yerel ürününüzü köyün sakinlerine ve misafirlerine tanıtın.",
  addCta: "İşletmeni ekle",
  addReviewNote: "Her başvuru yayımlanmadan önce incelenir.",
  addContactIntro: "Bilgilerinizi gönderin:",
  viewDetails: "Ayrıntıları gör",
  call: "Ara",
  openMap: "Haritayı aç",
  visitWebsite: "Siteyi ziyaret et",
  sendEmail: "E-posta gönder",
  backToList: "Tüm yerlere dön",
  detailAbout: "Hakkında",
  detailProducts: "Ürünler",
  detailServices: "Hizmetler",
  detailContact: "İletişim",
  detailHours: "Çalışma saatleri",
  detailLocation: "Nerede",
  detailGallery: "Galeri",
  detailAccessibility: "Erişilebilirlik",
  detailStory: "Hikâyesi",
  detailRelated: "Aglen’de yakınlarda",
  reportIssue: "Yanlış bilgi bildir",
  lastUpdated: "Güncellendi",
  closedDay: "Kapalı",
  badgeDelivery: "Teslimat",
  badgePickup: "Yerinden alım",
  badgeBooking: "Rezervasyon gerekli",
  badgeSeasonal: "Mevsimlik",
  badgeVerified: "Doğrulandı",
  badgeOpenNow: "Şu anda açık",
  badgeClosedNow: "Şu anda kapalı",
  badgeTemporarilyClosed: "Geçici olarak kapalı",
  emptyAll: "Henüz yer eklenmedi. Aglen’de bir işletmeniz varsa burada tanıtın.",
  emptyCategory: "Bu kategoride henüz yer yok. Başka bir kategori deneyin veya bir yerel işletme önerin.",
  emptyResults: "Bu arama için sonuç yok. Başka bir kelime deneyin veya filtreleri temizleyin.",
  notFound: "Bu yer bulunamadı. Tüm yerel işletmeleri görün.",
};

const el: BusinessesUiText = {
  heroEyebrow: "Αγοράστε τοπικά",
  heroTitle: "Τοπικές επιχειρήσεις στο Άγκλεν",
  heroSubtitle: "Ανακαλύψτε τα καταστήματα, τους παραγωγούς, τις υπηρεσίες και τους ανθρώπους που δίνουν ζωή στο χωριό.",
  heroTagline: "Αγοράστε τοπικά. Γνωρίστε τους ανθρώπους πίσω από το Άγκλεν.",
  heroCtaExplore: "Δείτε τα μέρη",
  heroCtaAdd: "Προσθέστε την επιχείρησή σας",
  searchLabel: "Αναζήτηση τοπικών επιχειρήσεων",
  searchPlaceholder: "Αναζητήστε κατάστημα, υπηρεσία ή τοπικό προϊόν…",
  filtersAria: "Πρόσθετα φίλτρα",
  categoriesAria: "Κατηγορίες",
  filterAll: "Όλα",
  filterOpenNow: "Ανοιχτά τώρα",
  filterDelivery: "Με παράδοση",
  filterPickup: "Παραλαβή από το σημείο",
  clearFilters: "Καθαρισμός φίλτρων",
  resultsCount: "Εμφανίζονται {count} μέρη",
  catFood: "Φαγητό & ποτό",
  catShops: "Καταστήματα",
  catProducers: "Τοπικοί παραγωγοί",
  catStay: "Διαμονή",
  catCrafts: "Χειροτεχνία & τέχνη",
  catServices: "Υπηρεσίες",
  catFarming: "Γεωργία",
  catOther: "Άλλα",
  featuredEyebrow: "Επιλογή της κοινότητας",
  featuredTitle: "Προτεινόμενα τοπικά μέρη",
  featuredBadge: "Προβεβλημένο μέρος",
  listTitle: "Τα μέρη του Άγκλεν",
  storiesEyebrow: "Ιστορίες",
  storiesTitle: "Οι άνθρωποι πίσω από το Άγκλεν",
  productsEyebrow: "Τοπικά προϊόντα",
  productsTitle: "Φτιαγμένο στο Άγκλεν",
  productsNote: "Δείτε ποιος προσφέρει τι και επικοινωνήστε απευθείας με τον παραγωγό.",
  addEyebrow: "Για τους κατοίκους",
  addTitle: "Έχετε επιχείρηση στο Άγκλεν;",
  addText:
    "Παρουσιάστε το κατάστημα, την υπηρεσία, το αγρόκτημα ή το τοπικό σας προϊόν στους κατοίκους και τους επισκέπτες του χωριού.",
  addCta: "Προσθέστε την επιχείρησή σας",
  addReviewNote: "Κάθε υποβολή ελέγχεται πριν δημοσιευθεί.",
  addContactIntro: "Στείλτε τα στοιχεία σας στο:",
  viewDetails: "Δείτε λεπτομέρειες",
  call: "Κλήση",
  openMap: "Άνοιγμα χάρτη",
  visitWebsite: "Επισκεφθείτε τον ιστότοπο",
  sendEmail: "Αποστολή email",
  backToList: "Πίσω σε όλα τα μέρη",
  detailAbout: "Σχετικά",
  detailProducts: "Προϊόντα",
  detailServices: "Υπηρεσίες",
  detailContact: "Επικοινωνία",
  detailHours: "Ωράριο",
  detailLocation: "Πού βρίσκεται",
  detailGallery: "Συλλογή",
  detailAccessibility: "Προσβασιμότητα",
  detailStory: "Η ιστορία",
  detailRelated: "Κοντά στο Άγκλεν",
  reportIssue: "Αναφορά λανθασμένης πληροφορίας",
  lastUpdated: "Ενημερώθηκε στις",
  closedDay: "Κλειστά",
  badgeDelivery: "Παράδοση",
  badgePickup: "Παραλαβή",
  badgeBooking: "Απαιτείται κράτηση",
  badgeSeasonal: "Εποχικό",
  badgeVerified: "Επιβεβαιωμένο",
  badgeOpenNow: "Ανοιχτά τώρα",
  badgeClosedNow: "Κλειστά τώρα",
  badgeTemporarilyClosed: "Προσωρινά κλειστό",
  emptyAll: "Δεν έχουν προστεθεί ακόμη μέρη. Αν έχετε επιχείρηση στο Άγκλεν, παρουσιάστε την εδώ.",
  emptyCategory: "Δεν υπάρχουν ακόμη μέρη σε αυτήν την κατηγορία. Δοκιμάστε άλλη κατηγορία ή προτείνετε μια τοπική επιχείρηση.",
  emptyResults: "Δεν υπάρχουν αποτελέσματα για αυτήν την αναζήτηση. Δοκιμάστε άλλη λέξη ή καθαρίστε τα φίλτρα.",
  notFound: "Αυτό το μέρος δεν βρέθηκε. Δείτε όλες τις τοπικές επιχειρήσεις.",
};

const ru: BusinessesUiText = {
  heroEyebrow: "Покупайте местное",
  heroTitle: "Местный бизнес в Ъглене",
  heroSubtitle: "Откройте для себя местные магазины, производителей, услуги и людей, которые дают жизнь селу.",
  heroTagline: "Покупайте местное. Познакомьтесь с людьми Ъглена.",
  heroCtaExplore: "Смотреть места",
  heroCtaAdd: "Добавить свой бизнес",
  searchLabel: "Поиск местного бизнеса",
  searchPlaceholder: "Ищите магазин, услугу или местный продукт…",
  filtersAria: "Дополнительные фильтры",
  categoriesAria: "Категории",
  filterAll: "Все",
  filterOpenNow: "Открыто сейчас",
  filterDelivery: "С доставкой",
  filterPickup: "Самовывоз",
  clearFilters: "Очистить фильтры",
  resultsCount: "Показано мест: {count}",
  catFood: "Еда и напитки",
  catShops: "Магазины",
  catProducers: "Местные производители",
  catStay: "Проживание",
  catCrafts: "Ремёсла и искусство",
  catServices: "Услуги",
  catFarming: "Сельское хозяйство",
  catOther: "Другое",
  featuredEyebrow: "Выбор сообщества",
  featuredTitle: "Рекомендуемые местные места",
  featuredBadge: "Представленное место",
  listTitle: "Места в Ъглене",
  storiesEyebrow: "Истории",
  storiesTitle: "Люди Ъглена",
  productsEyebrow: "Местные продукты",
  productsTitle: "Сделано в Ъглене",
  productsNote: "Посмотрите, кто что предлагает, и свяжитесь с производителем напрямую.",
  addEyebrow: "Для местных",
  addTitle: "У вас есть бизнес в Ъглене?",
  addText:
    "Представьте свой магазин, услугу, хозяйство или местный продукт жителям и гостям села.",
  addCta: "Добавить свой бизнес",
  addReviewNote: "Каждая заявка проверяется перед публикацией.",
  addContactIntro: "Отправьте данные на:",
  viewDetails: "Подробнее",
  call: "Позвонить",
  openMap: "Открыть карту",
  visitWebsite: "Перейти на сайт",
  sendEmail: "Отправить письмо",
  backToList: "Ко всем местам",
  detailAbout: "О месте",
  detailProducts: "Продукты",
  detailServices: "Услуги",
  detailContact: "Контакты",
  detailHours: "Часы работы",
  detailLocation: "Где находится",
  detailGallery: "Галерея",
  detailAccessibility: "Доступность",
  detailStory: "История",
  detailRelated: "Рядом в Ъглене",
  reportIssue: "Сообщить о неточности",
  lastUpdated: "Обновлено",
  closedDay: "Закрыто",
  badgeDelivery: "Доставка",
  badgePickup: "Самовывоз",
  badgeBooking: "По записи",
  badgeSeasonal: "Сезонно",
  badgeVerified: "Подтверждено",
  badgeOpenNow: "Открыто сейчас",
  badgeClosedNow: "Сейчас закрыто",
  badgeTemporarilyClosed: "Временно закрыто",
  emptyAll: "Места пока не добавлены. Если у вас есть бизнес в Ъглене, представьте его здесь.",
  emptyCategory: "В этой категории пока нет мест. Попробуйте другую категорию или предложите местный бизнес.",
  emptyResults: "По этому запросу ничего не найдено. Попробуйте другое слово или очистите фильтры.",
  notFound: "Это место не найдено. Посмотрите все местные компании.",
};

const ja: BusinessesUiText = {
  heroEyebrow: "地元で買う",
  heroTitle: "アグレンの地元のお店",
  heroSubtitle: "村に活気をもたらす商店、生産者、サービス、そして人々をご紹介します。",
  heroTagline: "地元で買う。アグレンの人々を知る。",
  heroCtaExplore: "お店を見る",
  heroCtaAdd: "お店を登録する",
  searchLabel: "地元のお店を検索",
  searchPlaceholder: "お店、サービス、地元の商品を検索…",
  filtersAria: "追加の絞り込み",
  categoriesAria: "カテゴリー",
  filterAll: "すべて",
  filterOpenNow: "営業中",
  filterDelivery: "配達あり",
  filterPickup: "店頭受取",
  clearFilters: "絞り込みを解除",
  resultsCount: "{count} 件を表示",
  catFood: "飲食",
  catShops: "商店",
  catProducers: "地元の生産者",
  catStay: "宿泊",
  catCrafts: "工芸・アート",
  catServices: "サービス",
  catFarming: "農業",
  catOther: "その他",
  featuredEyebrow: "地域が選んだお店",
  featuredTitle: "おすすめの地元のお店",
  featuredBadge: "紹介中のお店",
  listTitle: "アグレンのお店",
  storiesEyebrow: "ストーリー",
  storiesTitle: "アグレンを支える人々",
  productsEyebrow: "地元の産品",
  productsTitle: "アグレン産",
  productsNote: "どこで何が手に入るかを見て、生産者に直接ご連絡ください。",
  addEyebrow: "地元の方へ",
  addTitle: "アグレンでお店を営んでいますか？",
  addText: "お店、サービス、農場、地元の商品を村の住民と訪問者に紹介しましょう。",
  addCta: "お店を登録する",
  addReviewNote: "すべての申請は公開前に確認されます。",
  addContactIntro: "情報の送り先:",
  viewDetails: "詳細を見る",
  call: "電話する",
  openMap: "地図を開く",
  visitWebsite: "サイトを見る",
  sendEmail: "メールを送る",
  backToList: "すべてのお店に戻る",
  detailAbout: "紹介",
  detailProducts: "商品",
  detailServices: "サービス",
  detailContact: "連絡先",
  detailHours: "営業時間",
  detailLocation: "場所",
  detailGallery: "ギャラリー",
  detailAccessibility: "アクセシビリティ",
  detailStory: "ストーリー",
  detailRelated: "アグレンの近くのお店",
  reportIssue: "情報の誤りを報告",
  lastUpdated: "更新日",
  closedDay: "定休日",
  badgeDelivery: "配達",
  badgePickup: "店頭受取",
  badgeBooking: "要予約",
  badgeSeasonal: "季節営業",
  badgeVerified: "確認済み",
  badgeOpenNow: "営業中",
  badgeClosedNow: "営業時間外",
  badgeTemporarilyClosed: "一時休業",
  emptyAll: "まだお店が登録されていません。アグレンでお店を営んでいる方はこちらでご紹介ください。",
  emptyCategory: "このカテゴリーにはまだお店がありません。別のカテゴリーをお試しいただくか、地元のお店をご提案ください。",
  emptyResults: "該当するものが見つかりません。別の言葉でお試しいただくか、絞り込みを解除してください。",
  notFound: "このお店は見つかりませんでした。すべての地元のお店をご覧ください。",
};

const sr: BusinessesUiText = {
  heroEyebrow: "Купуј локално",
  heroTitle: "Локални бизниси у Аглену",
  heroSubtitle: "Откријте локалне радње, произвођаче, услуге и људе који дају живот селу.",
  heroTagline: "Купуј локално. Упознај људе иза Аглена.",
  heroCtaExplore: "Погледајте места",
  heroCtaAdd: "Додајте свој бизнис",
  searchLabel: "Претрага локалних бизниса",
  searchPlaceholder: "Тражите радњу, услугу или локални производ…",
  filtersAria: "Додатни филтери",
  categoriesAria: "Категорије",
  filterAll: "Све",
  filterOpenNow: "Тренутно отворено",
  filterDelivery: "Са доставом",
  filterPickup: "Преузимање на лицу места",
  clearFilters: "Обриши филтере",
  resultsCount: "Приказано места: {count}",
  catFood: "Храна и пиће",
  catShops: "Радње",
  catProducers: "Локални произвођачи",
  catStay: "Смештај",
  catCrafts: "Занати и уметност",
  catServices: "Услуге",
  catFarming: "Пољопривреда",
  catOther: "Остало",
  featuredEyebrow: "Избор заједнице",
  featuredTitle: "Издвојена локална места",
  featuredBadge: "Представљено место",
  listTitle: "Места у Аглену",
  storiesEyebrow: "Приче",
  storiesTitle: "Људи иза Аглена",
  productsEyebrow: "Локални производи",
  productsTitle: "Направљено у Аглену",
  productsNote: "Погледајте ко шта нуди и обратите се произвођачу директно.",
  addEyebrow: "За мештане",
  addTitle: "Имате бизнис у Аглену?",
  addText:
    "Представите своју радњу, услугу, газдинство или локални производ становницима и гостима села.",
  addCta: "Додајте свој бизнис",
  addReviewNote: "Свака пријава се прегледа пре објављивања.",
  addContactIntro: "Пошаљите податке на:",
  viewDetails: "Погледајте детаље",
  call: "Позовите",
  openMap: "Отвори мапу",
  visitWebsite: "Посетите сајт",
  sendEmail: "Пошаљите имејл",
  backToList: "Назад на сва места",
  detailAbout: "О месту",
  detailProducts: "Производи",
  detailServices: "Услуге",
  detailContact: "Контакт",
  detailHours: "Радно време",
  detailLocation: "Где се налази",
  detailGallery: "Галерија",
  detailAccessibility: "Приступачност",
  detailStory: "Прича",
  detailRelated: "У близини у Аглену",
  reportIssue: "Пријавите нетачну информацију",
  lastUpdated: "Ажурирано",
  closedDay: "Затворено",
  badgeDelivery: "Достава",
  badgePickup: "Преузимање",
  badgeBooking: "Уз резервацију",
  badgeSeasonal: "Сезонски",
  badgeVerified: "Потврђено",
  badgeOpenNow: "Тренутно отворено",
  badgeClosedNow: "Тренутно затворено",
  badgeTemporarilyClosed: "Привремено затворено",
  emptyAll: "Још нема додатих места. Ако имате бизнис у Аглену, представите га овде.",
  emptyCategory: "Још нема места у овој категорији. Пробајте другу категорију или предложите локални бизнис.",
  emptyResults: "Нема резултата за ову претрагу. Пробајте другу реч или обришите филтере.",
  notFound: "Ово место није пронађено. Погледајте све локалне бизнисе.",
};

const zh: BusinessesUiText = {
  heroEyebrow: "支持本地",
  heroTitle: "阿格伦的本地商家",
  heroSubtitle: "探索让村庄充满活力的商店、生产者、服务以及背后的人们。",
  heroTagline: "支持本地。认识阿格伦背后的人。",
  heroCtaExplore: "浏览店家",
  heroCtaAdd: "添加你的商家",
  searchLabel: "搜索本地商家",
  searchPlaceholder: "搜索商店、服务或本地产品…",
  filtersAria: "更多筛选",
  categoriesAria: "分类",
  filterAll: "全部",
  filterOpenNow: "正在营业",
  filterDelivery: "可配送",
  filterPickup: "到店自取",
  clearFilters: "清除筛选",
  resultsCount: "显示 {count} 个地点",
  catFood: "餐饮",
  catShops: "商店",
  catProducers: "本地生产者",
  catStay: "住宿",
  catCrafts: "手工艺与艺术",
  catServices: "服务",
  catFarming: "农业",
  catOther: "其他",
  featuredEyebrow: "社区精选",
  featuredTitle: "推荐的本地店家",
  featuredBadge: "精选店家",
  listTitle: "阿格伦的店家",
  storiesEyebrow: "故事",
  storiesTitle: "阿格伦背后的人",
  productsEyebrow: "本地产品",
  productsTitle: "阿格伦出品",
  productsNote: "看看谁提供什么，并直接联系生产者。",
  addEyebrow: "致本地居民",
  addTitle: "你在阿格伦经营吗？",
  addText: "把你的商店、服务、农场或本地产品介绍给村里的居民和来访的客人。",
  addCta: "添加你的商家",
  addReviewNote: "每份提交都会在发布前经过审核。",
  addContactIntro: "请将信息发送至：",
  viewDetails: "查看详情",
  call: "拨打电话",
  openMap: "打开地图",
  visitWebsite: "访问网站",
  sendEmail: "发送邮件",
  backToList: "返回全部店家",
  detailAbout: "关于",
  detailProducts: "产品",
  detailServices: "服务",
  detailContact: "联系方式",
  detailHours: "营业时间",
  detailLocation: "位置",
  detailGallery: "图库",
  detailAccessibility: "无障碍信息",
  detailStory: "故事",
  detailRelated: "阿格伦附近",
  reportIssue: "报告信息有误",
  lastUpdated: "更新于",
  closedDay: "休息",
  badgeDelivery: "配送",
  badgePickup: "自取",
  badgeBooking: "需预约",
  badgeSeasonal: "季节性",
  badgeVerified: "已核实",
  badgeOpenNow: "正在营业",
  badgeClosedNow: "现已打烊",
  badgeTemporarilyClosed: "暂停营业",
  emptyAll: "尚未添加任何店家。如果你在阿格伦经营，欢迎在此介绍。",
  emptyCategory: "此分类暂时还没有店家。请尝试其他分类，或推荐一家本地商家。",
  emptyResults: "没有符合此搜索的结果。请换个词或清除筛选。",
  notFound: "未找到该店家。查看全部本地商家。",
};

const hu: BusinessesUiText = {
  heroEyebrow: "Vásárolj helyben",
  heroTitle: "Helyi vállalkozások Aglenben",
  heroSubtitle: "Fedezze fel a helyi boltokat, termelőket, szolgáltatásokat és az embereket, akik életet adnak a falunak.",
  heroTagline: "Vásárolj helyben. Ismerd meg az Aglen mögötti embereket.",
  heroCtaExplore: "Helyek böngészése",
  heroCtaAdd: "Vállalkozás hozzáadása",
  searchLabel: "Helyi vállalkozások keresése",
  searchPlaceholder: "Keressen boltot, szolgáltatást vagy helyi terméket…",
  filtersAria: "További szűrők",
  categoriesAria: "Kategóriák",
  filterAll: "Mind",
  filterOpenNow: "Most nyitva",
  filterDelivery: "Kiszállítással",
  filterPickup: "Helyszíni átvétel",
  clearFilters: "Szűrők törlése",
  resultsCount: "{count} hely megjelenítve",
  catFood: "Étel és ital",
  catShops: "Boltok",
  catProducers: "Helyi termelők",
  catStay: "Szállás",
  catCrafts: "Kézművesség és művészet",
  catServices: "Szolgáltatások",
  catFarming: "Mezőgazdaság",
  catOther: "Egyéb",
  featuredEyebrow: "A közösség választása",
  featuredTitle: "Kiemelt helyi helyek",
  featuredBadge: "Bemutatott hely",
  listTitle: "Aglen helyei",
  storiesEyebrow: "Történetek",
  storiesTitle: "Az Aglen mögötti emberek",
  productsEyebrow: "Helyi termékek",
  productsTitle: "Aglenben készült",
  productsNote: "Nézze meg, ki mit kínál, és lépjen kapcsolatba közvetlenül a termelővel.",
  addEyebrow: "Helyieknek",
  addTitle: "Van vállalkozása Aglenben?",
  addText:
    "Mutassa be boltját, szolgáltatását, gazdaságát vagy helyi termékét a falu lakóinak és vendégeinek.",
  addCta: "Vállalkozás hozzáadása",
  addReviewNote: "Minden beküldést ellenőrzünk a közzététel előtt.",
  addContactIntro: "Küldje el adatait ide:",
  viewDetails: "Részletek",
  call: "Hívás",
  openMap: "Térkép megnyitása",
  visitWebsite: "Weboldal megtekintése",
  sendEmail: "E-mail küldése",
  backToList: "Vissza az összes helyhez",
  detailAbout: "Bemutatkozás",
  detailProducts: "Termékek",
  detailServices: "Szolgáltatások",
  detailContact: "Kapcsolat",
  detailHours: "Nyitvatartás",
  detailLocation: "Hol található",
  detailGallery: "Galéria",
  detailAccessibility: "Akadálymentesség",
  detailStory: "A történet",
  detailRelated: "A közelben Aglenben",
  reportIssue: "Hibás adat jelentése",
  lastUpdated: "Frissítve",
  closedDay: "Zárva",
  badgeDelivery: "Kiszállítás",
  badgePickup: "Átvétel",
  badgeBooking: "Előzetes egyeztetéssel",
  badgeSeasonal: "Szezonális",
  badgeVerified: "Ellenőrzött",
  badgeOpenNow: "Most nyitva",
  badgeClosedNow: "Most zárva",
  badgeTemporarilyClosed: "Átmenetileg zárva",
  emptyAll: "Még nincsenek hozzáadott helyek. Ha vállalkozása van Aglenben, mutassa be itt.",
  emptyCategory: "Ebben a kategóriában még nincsenek helyek. Próbáljon másik kategóriát, vagy ajánljon egy helyi vállalkozást.",
  emptyResults: "Nincs találat erre a keresésre. Próbáljon másik szót, vagy törölje a szűrőket.",
  notFound: "Ez a hely nem található. Nézze meg az összes helyi vállalkozást.",
};

export const businessesUiByLanguage: Record<LanguageCode, BusinessesUiText> = {
  bg,
  en,
  de,
  fr,
  es,
  it,
  ro,
  tr,
  el,
  ru,
  ja,
  sr,
  zh,
  hu,
};

export function categoryLabel(ui: BusinessesUiText, category: BusinessCategory): string {
  switch (category) {
    case "food":
      return ui.catFood;
    case "shops":
      return ui.catShops;
    case "producers":
      return ui.catProducers;
    case "stay":
      return ui.catStay;
    case "crafts":
      return ui.catCrafts;
    case "services":
      return ui.catServices;
    case "farming":
      return ui.catFarming;
    case "other":
      return ui.catOther;
  }
}

// Category glyphs are decorative only — every category is also named in text,
// so status and type are never conveyed by icon or colour alone.
export const categoryEmoji: Record<BusinessCategory, string> = {
  food: "🍲",
  shops: "🛒",
  producers: "🫙",
  stay: "🛏",
  crafts: "🧶",
  services: "🔧",
  farming: "🌾",
  other: "📍",
};
